home/urls.py
from django.urls import path

from . import views

app_name='home'
urlpatterns = [
    path('', views.index, name='home'),
    path('what/', views.what, name='what'),
    path('how/', views.how, name='how'),
    path('email/', views.email_list, name='email'),
    path('projects/', views.projects, name='projects'),
    path('volunteer/', views.volunteer, name='volunteer'),
    path('privacy/', views.privacy, name='privacy')
]

rmd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

from home import views

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path(
        'sitemap.xml', 
        sitemap, 
        {'sitemaps': sitemaps}, 
        name='django.contrib.sitemaps.views.sitemap'
    )
]

home/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

class EmailList(models.Model):
    first_name = models.CharField(max_length=50)
    email = models.EmailField()

class Volunteer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone_number = PhoneNumberField(blank=True)
    description = models.CharField(max_length=1000)

home/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget

from .models import EmailList, Volunteer

class EmailForm(forms.ModelForm):
    class Meta:
        model = EmailList
        fields = ('first_name', 'email')

class VolunteerForm(forms.ModelForm):
    phone_number = PhoneNumberField(widget=PhoneNumberPrefixWidget)
    description = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Volunteer
        fields = ('first_name', 'last_name', 'email', 'phone_number', 'description')

home/views.py
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail, EmailMessage, EmailMultiAlternatives
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from .forms import EmailForm, VolunteerForm
from .models import EmailList, Volunteer


def index(request):
    return render(request, 'home/index.html')


def what(request):
    return render(request, 'home/what.html')


def how(request):
    return render(request, 'home/how.html')


def projects(request):
    return render(request, 'home/projects.html')

def privacy(request):
    return render(request, 'home/privacy.html')

def email_list(request):
    if request.method == 'POST':
        email_list_form = EmailForm(data=request.POST)
        if email_list_form.is_valid():
            email_list_form.save()
            msg_html = render_to_string(
                'email/email_list_signup.html',
                {'first_name': email_list_form.cleaned_data['first_name']}
            )
            text_content = strip_tags(msg_html)
            msg = EmailMultiAlternatives(
                'Reform MI Dems Email List Signup',
                text_content,
                from_email=settings.EMAIL_HOST_USER,
                to=[email_list_form.cleaned_data['email']],
                bcc=[settings.EMAIL_BCC]
            )
            msg.attach_alternative(msg_html, "text/html")
            msg.send()
            messages.success(request, 'You have been added to the email list')
    else:
        email_list_form = EmailForm()
    return render(request, 'home/email_list.html', {'email_list_form': email_list_form})


def volunteer(request):
    if request.method == 'POST':
        volunteer_form = VolunteerForm(data=request.POST)
        if volunteer_form.is_valid():
            volunteer_form.save()
            msg_html = render_to_string(
                'email/volunteer_signup.html',
                {'first_name':volunter_form.cleaned_data['first_name']}
            )
            text_content = strip_tags(msg_html)
            msg = EmailMultiAlternatives(
                'Reform MI Dems Volunteer Signup',
                text_content,
                from_email=settings.EMAIL_HOST_USER,
                to=[email_list_form.cleaned_data['email']],
                bcc=[settings.EMAIL_BCC]
            )
            msg.attach_alternative(msg_html, "text/html")
            msg.send()
            messages.success(request, 'Thank you for volunteering, we will reach out to you shortly')
    else:
        volunteer_form = VolunteerForm()
    return render(request, 'home/volunteer.html', {'volunteer_form': volunteer_form})

home/templates/home/email_list.html
{% extends "base.html" %}

{% block title %}Reform MI Dems{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <h2>Sign up for the email list </h2>
        <form action="." method="post">
            <table class="table">
                {{ email_list_form.as_table }}
                {% csrf_token %}
            </table>
            <p><input type="submit" value="Sign up"></p>
        </form>
    </div>
</div>
{% endblock %}

home/templates/home/how.html
{% extends "base.html" %}

{% block title %}Reform MI Dems{% endblock %}

{% block content %}
<div class="container">
    <h2>
        <u>Why open-source?</u>
    </h2>
    <h3>
        Open source is a way for many individuals to volunteer and contribute to tools and centralized resources that everyone can use.
    </h3>
    <h2>
        <u>What can I do to help?</u>
    </h2>
    <h3>
        You can sign up to volunteer <a href="{% url 'home:volunteer' %}">here</a>
    </h3>
</div>
{% endblock %}

home/templates/home/index.html
{% extends "base.html" %}

{% block title %}Reform MI Dems{% endblock %}

{% block content %}
<div class="container">

    <div class="jumbotron text-center">
        <h1>
            Reform MI Dems
        </h1>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="jumbotron text-center">
                <a href="/what">
                    <h2><u>What</u></h2>
                </a>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="jumbotron text-center">
                <a href="/how">
                    <h2><u>How</u></h2>
                </a>
            </div>
        </div>
    </div>
    <div class="jumbotron text-center">
        <a href="/projects">
            <h2><u>Project List</u></h2>
        </a>
    </div>
</div>

{% endblock %}

home/templates/home/privacy.html
{% extends "base.html" %}

{% block title %}Reform MI Dems{% endblock %}

{% block content %}
<div class="container">
        <h1>Privacy Policy</h1>


        <p>Effective date: March 17, 2019</p>
        
        
        <p>Reform MI Dems ("us", "we", or "our") operates the reformmidems.com website (hereinafter referred to as the "Service").</p>
        
        <p>This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>
        
        <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from reformmidems.com</p>
        
        <h2>Definitions</h2>
        <ul>
            <li>
                <p><strong>Service</strong></p>
                        <p>Service is the reformmidems.com website operated by Reform MI Dems</p>
                    </li>
            <li>
                <p><strong>Personal Data</strong></p>
                <p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
            </li>
            <li>
                <p><strong>Usage Data</strong></p>
                <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
            </li>
            <li>
                <p><strong>Cookies</strong></p>
                <p>Cookies are small files stored on your device (computer or mobile device).</p>
            </li>
            </ul>
        
        
        <h2>Information Collection and Use</h2>
        <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
        
        <h3>Types of Data Collected</h3>
        
        <h4>Personal Data</h4>
        <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>
        
        <ul>
            <li>Email address</li>    <li>First name and last name</li>    <li>Phone number</li>        <li>Cookies and Usage Data</li>
        </ul>
        
        <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by contacting us.</p>
        
        <h4>Usage Data</h4>
        
        <p>We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
        
        
        <h4>Tracking & Cookies Data</h4>
        <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
        <p>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.</p>
        <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
        <p>Examples of Cookies we use:</p>
        <ul>
            <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
            <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
            <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
            </ul>
        
        <h2>Use of Data</h2> 
        <p>Reform MI Dems uses the collected data for various purposes:</p>    
        <ul>
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
            <li>To provide customer support</li>
            <li>To gather analysis or valuable information so that we can improve our Service</li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
            <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li></ul>
        
        
        
        <h2>Transfer of Data</h2>
        <p>Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
        <p>If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.</p>
        <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
        <p>Reform MI Dems will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
        
        <h2>Disclosure of Data</h2>
        
        <h3>Disclosure for Law Enforcement</h3>
        <p>Under certain circumstances, Reform MI Dems may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
        
        <h3>Legal Requirements</h3>
        <p>Reform MI Dems may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul>
            <li>To comply with a legal obligation</li>
            <li>To protect and defend the rights or property of Reform MI Dems</li>
            <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>To protect the personal safety of users of the Service or the public</li>
            <li>To protect against legal liability</li>
        </ul>
        
        <h2>Security of Data</h2>
        <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
        
        
        
        <h2>Service Providers</h2>
        <p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>
        <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
        
        <h3>Analytics</h3>
        <p>We may use third-party Service Providers to monitor and analyse the use of our Service.</p>    
        <ul>
                        <li>
                <p><strong>Piwik / Matomo</strong></p>
                <p>Piwik or Matomo is a web analytics service. You can visit their Privacy Policy page here: <a href="https://matomo.org/privacy-policy">https://matomo.org/privacy-policy</a></p>
            </li>
                                </ul>
        
        <h2>Links to Other Sites</h2>
        <p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
        <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
        
        
        <h2>Children's Privacy</h2>
        <p>Our Service does not address anyone under the age of 18 ("Children").</p>
        <p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>
        
        
        <h2>Changes to This Privacy Policy</h2>
        <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
        <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
        <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
        
        
        <h2>Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, please contact us:</p>
        <ul>
                <li>By email: wileyrya@gmail.com</li>
                  
                </ul>
</div>
{% endblock %}

home/templates/home/projects.html
{% extends "base.html" %}

{% block title %}Reform MI Dems{% endblock %}

{% block content %}
<div class="container">
    <h2>
        <a href="https://gitlab.com/rdubwiley/election-analysis-starter-kit">
            <u>Election Analysis Starter Kit</u>
        </a>
    </h2>
    <h2>
        <a href="https://gitlab.com/rdubwiley/voter_file_api">
            <u>Voter File API</u>
        </a>
    </h2>
</div>
{% endblock %}

home/templates/home/volunteer.html
{% extends "base.html" %}

{% block title %}Reform MI Dems{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <h2 class='text-center'>RMD needs volunteers to help with our projects</h2>
        <h2 class='text-center'>Sign up here!</h2>
        <form action="." method="post">
            <table class="table">
                {{ volunteer_form.as_table }}
                {% csrf_token %}
            </table>
            <p><input type="submit" value="Sign up"></p>
        </form>
    </div>
</div>
{% endblock %}

home/templates/home/what.html
{% extends "base.html" %}

{% block title %}Reform MI Dems{% endblock %}

{% block content %}
<div class="container">
    <h2>
        <u>Who are we?</u>
    </h2>
    <h3>
        Reform MI Dems is dedicated to improving the Democratic Party through open-source technologies. Through this, we hope to make the party and related political systems more transparent, more open, and more fair.
    </h3>
    <h2>
        <u>What things do we do?</u>
    </h2>
    <h3>
        We find problems that limit open participation and use open technologies like the web to solve them. Our first project was an open source app that made it easier for individuals to sign up for the Michigan Democratic Party through a free membership form.
    </h3>
    <h2>
        <u>How do we contact you?</u>
    </h2>
    <h3>
        The best way to contact us is through: ryan.wiley@reformmidems.com
    </h3>
</div>
{% endblock %}